builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - netbsd
      - openbsd
    tags:
      - embeddedClient

archives:
  - format_overrides:
      - goos: windows
        format: zip

nfpms:
  - formats:
      - apk
      - deb
      - rpm

    vendor: KPWeb
    homepage: https://github.com/Photonios/kpweb
    maintainer: Swen Kooij <swenkooij@gmail.com>
    description: Web server that serves a KeePass database.
    license: MIT

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: Photonios
    name: kpweb
