name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: cd client; yarn install

      - run: make client

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: server
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
